#!/usr/bin/env bash
# leaf.sh - Beautiful documentation and landing page generator
# Version: 2.2.0 - Now using myst.sh templating engine
# Generated by hammer.sh

set -euo pipefail

# Get script directory
if command -v dirname >/dev/null 2>&1; then
	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
	# Fallback if dirname is not available
	SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" && pwd)"
fi
TEMPLATES_DIR="${SCRIPT_DIR}/templates"

# Colors for output
export FORCE_COLOR=${FORCE_COLOR:-}
if [[ -z "$FORCE_COLOR" ]]; then
	if [[ "$FORCE_COLOR" = "1" ]]; then
		export RED='\033[0;31m'
		export GREEN='\033[0;32m'
		export YELLOW='\033[1;33m'
		export BLUE='\033[0;34m'
		export CYAN='\033[0;36m'
		export MAGENTA='\033[0;35m'
		export BOLD='\033[1m'
		export NC='\033[0m'
	else
		export RED=''
		export GREEN=''
		export YELLOW=''
		export BLUE=''
		export CYAN=''
		export MAGENTA=''
		export BOLD=''
		export NC=''
	fi
elif [[ -t 1 ]] && [[ -t 2 ]]; then
	export RED='\033[0;31m'
	export GREEN='\033[0;32m'
	export YELLOW='\033[1;33m'
	export BLUE='\033[0;34m'
	export CYAN='\033[0;36m'
	export MAGENTA='\033[0;35m'
	export BOLD='\033[1m'
	export NC='\033[0m'
else
	export RED=''
	export GREEN=''
	export YELLOW=''
	export BLUE=''
	export CYAN=''
	export MAGENTA=''
	export BOLD=''
	export NC=''
fi

# Default configuration
PROJECT_DIR="${1:-.}"
OUTPUT_DIR="${PROJECT_DIR}/docs"
MODE="docs"
LOGO_PATH=""
BASE_PATH="/"
GITHUB_URL="https://github.com/butter-sh"
PROJECTS_FILE=""
PROJECTS_JSON=""

# Helper functions
log_info() {
	echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
	echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
	echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
	echo -e "${RED}✗${NC} $1"
}

log_debug() {
	if [[ "${DEBUG:-0}" == "1" ]]; then
		echo -e "${MAGENTA}🔍${NC} $1"
	fi
}

# Find myst.sh
find_myst() {
	local myst_path=""
	
	# Try .arty/bin/myst first
	if [[ -x "${SCRIPT_DIR}/.arty/bin/myst" ]]; then
		myst_path="${SCRIPT_DIR}/.arty/bin/myst"
	# Try sibling myst directory
	elif [[ -x "${SCRIPT_DIR}/../myst/myst.sh" ]]; then
		myst_path="${SCRIPT_DIR}/../myst/myst.sh"
	# Try system myst
	elif command -v myst &>/dev/null; then
		myst_path="myst"
	else
		log_error "myst.sh not found. Please install it or run 'arty deps' in leaf.sh directory"
		return 1
	fi
	
	echo "$myst_path"
}

# Render template with myst
render_with_myst() {
	local template="$1"
	local output="$2"
	local json_file="$3"
	
	local myst_path=$(find_myst)
	[[ -z "$myst_path" ]] && return 1
	
	log_debug "Using myst: $myst_path"
	log_debug "Template: $template"
	log_debug "Output: $output"
	log_debug "JSON file: $json_file"
	
	# Create output directory
	mkdir -p "$(dirname "$output")"
	
	# Check if template exists
	if [[ ! -f "$template" ]]; then
		log_error "Template not found: $template"
		return 1
	fi
	
	# Check if JSON file exists
	if [[ ! -f "$json_file" ]]; then
		log_error "JSON data file not found: $json_file"
		return 1
	fi
	
	# Render with myst - capture both stdout and stderr
	local myst_output
	local myst_exit_code
	
	if myst_output=$(bash "$myst_path" render \
		-t "$template" \
		-j "$json_file" \
		-p "${TEMPLATES_DIR}/partials" \
		-o "$output" 2>&1); then
		myst_exit_code=0
	else
		myst_exit_code=$?
	fi
	
	# Show myst output only if debug is enabled or if there was an error
	if [[ "${DEBUG:-0}" == "1" ]] || [[ $myst_exit_code -ne 0 ]]; then
		echo "$myst_output" | grep -v "^\[" || true
	fi
	
	if [[ $myst_exit_code -ne 0 ]]; then
		log_error "Myst rendering failed with exit code $myst_exit_code"
		return $myst_exit_code
	fi
	
	# Verify output was created
	if [[ ! -f "$output" ]]; then
		log_error "Myst did not create output file: $output"
		return 1
	fi
	
	return 0
}

# Check dependencies
check_dependencies() {
	local missing_deps=()

	if ! command -v yq &>/dev/null; then
		missing_deps+=("yq")
	fi

	if ! command -v jq &>/dev/null; then
		missing_deps+=("jq")
	fi

	if [ ${#missing_deps[@]} -gt 0 ]; then
		log_error "Missing required dependencies: ${missing_deps[*]}"
		log_info "Install yq: https://github.com/mikefarah/yq#install"
		log_info "Install jq: https://stedolan.github.io/jq/download/"
		return 1
	fi

	# Check for myst
	if ! find_myst >/dev/null 2>&1; then
		log_error "myst.sh not found"
		log_info "Run 'arty deps' in the leaf.sh directory to install dependencies"
		return 1
	fi

	return 0
}

# Show usage
show_usage() {
	cat <<EOF
${CYAN}╔═══════════════════════════════════════════╗${NC}
${CYAN}║                                           ║${NC}
${CYAN}║   🌿 leaf.sh - Documentation Generator   ║${NC}
${CYAN}║                                           ║${NC}
${CYAN}╚═══════════════════════════════════════════╝${NC}

${GREEN}DESCRIPTION:${NC}
    leaf.sh generates beautiful static HTML documentation from arty.sh projects
    and creates stylish landing pages for butter.sh with modern design.
    
    ${CYAN}Now powered by myst.sh templating engine!${NC}

${GREEN}USAGE:${NC}
    ${CYAN}# Generate documentation for arty.sh project${NC}
    leaf.sh [project-dir] [options]
    
    ${CYAN}# Generate butter.sh landing page${NC}
    leaf.sh --landing [options]

${GREEN}OPTIONS:${NC}
    ${YELLOW}--landing${NC}              Generate butter.sh landing page instead of docs
    ${YELLOW}--logo${NC} PATH            Path to logo/icon file
    ${YELLOW}--base-path${NC} PATH       Base path for HTML links (default: /)
    ${YELLOW}--github${NC} URL           GitHub organization URL
    ${YELLOW}--projects${NC} JSON        JSON array of projects for landing page
    ${YELLOW}--projects-file${NC} FILE   JSON file containing projects array
    ${YELLOW}-o, --output${NC} DIR       Output directory (default: docs)
    ${YELLOW}-h, --help${NC}             Show this help message
    ${YELLOW}--version${NC}              Show version information
    ${YELLOW}--debug${NC}                Enable debug output

${GREEN}DEPENDENCIES:${NC}
    • ${YELLOW}yq${NC} - YAML parser (required)
    • ${YELLOW}jq${NC} - JSON processor (required)
    • ${YELLOW}myst.sh${NC} - Templating engine (required)

${GREEN}VERSION:${NC}
    leaf.sh v2.2.0

EOF
}

# Show version
show_version() {
	cat <<EOF
${CYAN}leaf.sh${NC} version ${GREEN}2.2.0${NC}
Part of the ${CYAN}butter.sh${NC} ecosystem

${BLUE}Powered by:${NC}
  • myst.sh templating engine
  • yq YAML parser
  • jq JSON processor

${BLUE}GitHub:${NC} https://github.com/butter-sh/leaf.sh
EOF
}

# Parse command line arguments
parse_args() {
	local projects_json=""
	PROJECTS_JSON=""

	while [[ $# -gt 0 ]]; do
		case $1 in
		-h | --help)
			show_usage
			exit 0
			;;
		--version)
			show_version
			exit 0
			;;
		--debug)
			DEBUG=1
			shift
			;;
		--landing)
			MODE="landing"
			shift
			;;
		--logo)
			LOGO_PATH="$2"
			shift 2
			;;
		--base-path)
			BASE_PATH="$2"
			shift 2
			;;
		--github)
			GITHUB_URL="$2"
			shift 2
			;;
		--projects)
			projects_json="$2"
			shift 2
			;;
		--projects-file)
			PROJECTS_FILE="$2"
			shift 2
			;;
		-o | --output)
			OUTPUT_DIR="$2"
			shift 2
			;;
		-*)
			log_error "Unknown option: $1"
			echo
			show_usage
			exit 1
			;;
		*)
			PROJECT_DIR="$1"
			shift
			;;
		esac
	done

	if [[ -n "$projects_json" ]]; then
		PROJECTS_JSON="$projects_json"
	fi
}

# Parse YAML using yq
parse_yaml() {
	local file="$1"
	local key="$2"

	if [[ ! -f "$file" ]]; then
		log_debug "YAML file not found: $file"
		echo ""
		return
	fi

	local value=$(yq eval ".${key}" "$file" 2>/dev/null | grep -v '^null$' || echo "")
	log_debug "Parsed ${key} from ${file}: ${value}"
	echo "$value"
}

# Validate and parse JSON
parse_json() {
	local json_input="$1"
	local query="${2:-.}"

	log_debug "Parsing JSON with query: $query"

	local result
	if result=$(echo "$json_input" | jq -r "$query" 2>/dev/null); then
		log_debug "JSON parsed successfully"
		echo "$result"
		return 0
	else
		log_error "Invalid JSON format"
		return 1
	fi
}

# Validate projects JSON
validate_projects_json() {
	local json="$1"

	log_debug "Validating projects JSON structure"

	if ! echo "$json" | jq -e 'type == "array"' >/dev/null 2>&1; then
		log_error "Projects JSON must be an array"
		return 1
	fi

	local count=$(echo "$json" | jq 'length')
	if [[ "$count" -eq 0 ]]; then
		log_warn "Projects JSON array is empty"
	fi

	log_debug "Found $count project(s) in JSON"
	return 0
}

# Read JSON from file
read_json_file() {
	local file="$1"

	if [[ ! -f "$file" ]]; then
		log_error "JSON file not found: $file"
		return 1
	fi

	log_debug "Reading JSON from file: $file"

	local json
	if json=$(jq -c '.' "$file" 2>/dev/null); then
		log_success "JSON file loaded successfully"
		echo "$json"
		return 0
	else
		log_error "Failed to parse JSON file: $file"
		return 1
	fi
}

# Read file safely
read_file() {
	local file="$1"
	if [[ -f "$file" ]]; then
		cat "$file"
	else
		log_debug "File not found: $file"
		echo ""
	fi
}

# Detect language from file extension
detect_language() {
	local file="$1"
	local ext="${file##*.}"

	case "$ext" in
	sh | bash) echo "bash" ;;
	js) echo "javascript" ;;
	ts) echo "typescript" ;;
	py) echo "python" ;;
	rb) echo "ruby" ;;
	go) echo "go" ;;
	rs) echo "rust" ;;
	java) echo "java" ;;
	c | h) echo "c" ;;
	cpp | cc | cxx | hpp) echo "cpp" ;;
	*) echo "plaintext" ;;
	esac
}

# Get icon path
get_icon() {
	if [[ -n "$LOGO_PATH" && -f "$LOGO_PATH" ]]; then
		log_debug "Using custom logo: $LOGO_PATH"
		echo "$LOGO_PATH"
		return
	fi

	local icon_dir="${PROJECT_DIR}/_assets/icon"
	local icon_files=("icon.svg" "icon-v2.svg" "icon-simple.svg" "icon.png")

	for icon_file in "${icon_files[@]}"; do
		if [[ -f "${icon_dir}/${icon_file}" ]]; then
			log_debug "Found icon: ${icon_dir}/${icon_file}"
			echo "${icon_dir}/${icon_file}"
			return
		fi
	done

	echo ""
}

# Scan source files
scan_source_files() {
	local files=()

	log_debug "Scanning source files in: $PROJECT_DIR"

	while IFS= read -r -d $'\0' file; do
		local rel_path="${file#${PROJECT_DIR}/}"
		if [[ "$rel_path" =~ ^(docs|node_modules|\.git|\.)|\\.min\\. ]]; then
			continue
		fi
		files+=("$file")
		log_debug "Found source file: $rel_path"
	done < <(find "$PROJECT_DIR" -type f \( -name "*.sh" -o -name "*.bash" -o -name "*.js" -o -name "*.py" -o -name "*.rb" -o -name "*.go" -o -name "*.rs" \) -print0 2>/dev/null || true)

	printf '%s\n' "${files[@]}"
}

# Scan example files
scan_examples() {
	local examples_dir="${PROJECT_DIR}/examples"
	local examples=()

	if [[ ! -d "$examples_dir" ]]; then
		log_debug "Examples directory not found: $examples_dir"
		return
	fi

	log_debug "Scanning examples in: $examples_dir"

	while IFS= read -r -d $'\0' file; do
		examples+=("$file")
		log_debug "Found example: ${file#${examples_dir}/}"
	done < <(find "$examples_dir" -type f -print0 2>/dev/null || true)

	printf '%s\n' "${examples[@]}"
}

# Generate source files HTML
generate_source_html() {
	local sources=("$@")
	local html=""

	for file in "${sources[@]}"; do
		[[ ! -f "$file" ]] && continue
		local name=$(basename "$file")
		local rel="${file#${PROJECT_DIR}/}"
		local lang=$(detect_language "$file")
		local code=$(cat "$file" | jq -Rs .)
		
		html+="<div class=\"bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden\">"
		html+="<div class=\"bg-gradient-to-r from-blue-500 to-blue-600 px-6 py-4\">"
		html+="<h3 class=\"text-xl font-semibold text-white\">${name}</h3>"
		html+="<p class=\"text-blue-100 text-sm\">${rel}</p></div>"
		html+="<div class=\"p-6\"><pre><code class=\"language-${lang}\">${code}</code></pre></div></div>"
	done

	[[ -z "$html" ]] && html="<p class=\"text-center text-slate-600\">No source files found.</p>"
	echo "$html"
}

# Generate examples HTML
generate_examples_html() {
	local examples=("$@")
	local html=""

	for file in "${examples[@]}"; do
		[[ ! -f "$file" ]] && continue
		local name=$(basename "$file")
		local lang=$(detect_language "$file")
		local code=$(cat "$file" | jq -Rs .)
		
		html+="<div class=\"bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden\">"
		html+="<div class=\"bg-gradient-to-r from-green-500 to-green-600 px-6 py-4\">"
		html+="<h3 class=\"text-xl font-semibold text-white\">${name}</h3></div>"
		html+="<div class=\"p-6\"><pre><code class=\"language-${lang}\">${code}</code></pre></div></div>"
	done

	[[ -z "$html" ]] && html="<p class=\"text-center text-slate-600\">No examples found.</p>"
	echo "$html"
}

# Generate documentation page
generate_docs_page() {
	log_info "Generating documentation..."

	local arty_yml="${PROJECT_DIR}/arty.yml"
	local readme_md="${PROJECT_DIR}/README.md"

	# Parse project metadata
	local project_name=$(parse_yaml "$arty_yml" "name")
	local project_version=$(parse_yaml "$arty_yml" "version")
	local project_desc=$(parse_yaml "$arty_yml" "description")

	[[ -z "$project_name" ]] && project_name=$(basename "$PROJECT_DIR")

	log_debug "Project: $project_name v$project_version"

	# Read README
	local readme_content=$(read_file "$readme_md")
	if [[ -z "$readme_content" ]]; then
		log_warn "README.md not found, using placeholder"
		readme_content="No README.md file found in project."
	fi

	# Get icon
	local icon_path=$(get_icon)
	local icon_svg=""
	if [[ -n "$icon_path" ]]; then
		icon_svg=$(cat "$icon_path")
		log_success "Loaded icon from: ${icon_path#${PROJECT_DIR}/}"
	else
		log_warn "No icon found, using default"
		icon_svg='<svg class="w-full h-full" fill="currentColor" viewBox="0 0 24 24"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>'
	fi

	# Scan files
	local source_files=($(scan_source_files))
	local example_files=($(scan_examples))

	log_info "Found ${#source_files[@]} source files and ${#example_files[@]} examples"

	# Generate HTML for sources and examples
	local src_html=$(generate_source_html "${source_files[@]}")
	local ex_html=$(generate_examples_html "${example_files[@]}")

	# Create JSON data file for myst
	local data_file="/tmp/leaf_docs_$$.json"
	jq -n \
		--arg name "$project_name" \
		--arg version "${project_version:-1.0.0}" \
		--arg desc "${project_desc:-Documentation}" \
		--arg icon "$icon_svg" \
		--arg readme "$readme_content" \
		--arg github "$GITHUB_URL" \
		--arg base "$BASE_PATH" \
		--arg src_html "$src_html" \
		--arg ex_html "$ex_html" \
		'{
			page_title: ($name + " - Documentation"),
			page_description: $desc,
			base_path: $base,
			project_name: $name,
			project_version: $version,
			project_description: $desc,
			icon: $icon,
			readme_content: $readme,
			github_url: $github,
			source_files_html: $src_html,
			examples_html: $ex_html,
			myst_enabled: "true"
		}' > "$data_file"

	# Render with myst
	if ! render_with_myst \
		"${TEMPLATES_DIR}/docs.html.myst" \
		"${OUTPUT_DIR}/index.html" \
		"$data_file"; then
		log_error "Failed to render documentation"
		rm -f "$data_file"
		return 1
	fi

	rm -f "$data_file"
	log_success "Documentation generated at: ${OUTPUT_DIR}/index.html"
}

# Generate landing page
generate_landing_page() {
	log_info "Generating butter.sh landing page..."

	mkdir -p "$OUTPUT_DIR"

	# Default projects
	local projects_default='[
		{"url":"https://hammer.sh","label":"hammer.sh","desc":"Configurable bash project generator","class":"card-project"},
		{"url":"https://arty.sh","label":"arty.sh","desc":"Bash library repository manager","class":"card-project"},
		{"url":"https://leaf.sh","label":"leaf.sh","desc":"Beautiful documentation generator","class":"card-project"}
	]'

	local projects=""

	# Load projects (priority: file > arg > default)
	if [[ -n "$PROJECTS_FILE" ]]; then
		log_info "Loading projects from file: $PROJECTS_FILE"
		if projects=$(read_json_file "$PROJECTS_FILE"); then
			if validate_projects_json "$projects"; then
				log_success "Projects JSON loaded and validated from file"
			else
				return 1
			fi
		else
			return 1
		fi
	elif [[ -n "$PROJECTS_JSON" ]]; then
		log_info "Using projects from command line"
		if parse_json "$PROJECTS_JSON" >/dev/null; then
			projects="$PROJECTS_JSON"
			if validate_projects_json "$projects"; then
				log_success "Projects JSON validated"
			else
				return 1
			fi
		else
			return 1
		fi
	else
		log_info "Using default butter.sh projects"
		projects="$projects_default"
	fi

	# Get logo
	local logo_svg=""
	if [[ -n "$LOGO_PATH" && -f "$LOGO_PATH" ]]; then
		logo_svg=$(cat "$LOGO_PATH")
		log_success "Using custom logo: $LOGO_PATH"
	else
		local butter_logo="${SCRIPT_DIR}/../butter.sh/_assets/brand/cube-carbon-light.svg"
		if [[ -f "$butter_logo" ]]; then
			logo_svg=$(cat "$butter_logo")
			log_success "Using butter.sh brand logo"
		else
			log_warn "Using default fallback logo"
			logo_svg='<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>'
		fi
	fi

	# Create JSON data file for myst
	local data_file="/tmp/leaf_landing_$$.json"
	jq -n \
		--arg logo "$logo_svg" \
		--arg base "$BASE_PATH" \
		--arg github "$GITHUB_URL" \
		--argjson projects "$projects" \
		'{
			page_title: "butter.sh - Modern Bash Development Ecosystem",
			page_description: "A collection of modern bash development tools",
			base_path: $base,
			logo: $logo,
			site_name: "butter.sh",
			github_url: $github,
			hero_tagline: "Modern bash development tools for the command line renaissance",
			primary_cta_text: "Explore Projects",
			primary_cta_url: $github,
			secondary_cta_text: "Learn More",
			secondary_cta_url: "#projects",
			projects_section_title: "Our Projects",
			projects_json: $projects,
			footer_tagline: "Building the future of bash development",
			generator_credit: "true",
			myst_enabled: "true"
		}' > "$data_file"

	# Render with myst
	if ! render_with_myst \
		"${TEMPLATES_DIR}/landing.html.myst" \
		"${OUTPUT_DIR}/index.html" \
		"$data_file"; then
		log_error "Failed to render landing page"
		rm -f "$data_file"
		return 1
	fi

	rm -f "$data_file"
	log_success "Landing page generated at: ${OUTPUT_DIR}/index.html"
}

# Main function
main() {
	# Check dependencies first
	if ! check_dependencies; then
		exit 1
	fi

	parse_args "$@"

	# Only show banner if not in test mode
	if [[ "${LEAF_TEST_MODE:-0}" != "1" ]]; then
		echo -e "${CYAN}"
		echo "╔═══════════════════════════════════════════╗"
		echo "║                                           ║"
		echo "║      🌿 leaf.sh Generator v2.2 🌿        ║"
		echo "║      Powered by myst.sh templating       ║"
		echo "║                                           ║"
		echo "╚═══════════════════════════════════════════╝"
		echo -e "${NC}"
		echo
	fi

	if [[ "$MODE" == "landing" ]]; then
		generate_landing_page
	else
		# Documentation mode
		if [[ ! -d "$PROJECT_DIR" ]]; then
			log_error "Project directory not found: $PROJECT_DIR"
			exit 1
		fi

		log_info "Scanning project: $PROJECT_DIR"
		generate_docs_page
	fi

	# Only show completion message if not in test mode
	if [[ "${LEAF_TEST_MODE:-0}" != "1" ]]; then
		echo
		echo -e "${GREEN}═══════════════════════════════════════════${NC}"
		echo -e "${GREEN}Generation complete! 🎉${NC}"
		echo -e "${GREEN}═══════════════════════════════════════════${NC}"
		echo
		echo -e "📂 Output: ${CYAN}${OUTPUT_DIR}/index.html${NC}"
		echo -e "🌐 Open: ${BLUE}file://${OUTPUT_DIR}/index.html${NC}"
		echo
	fi
}

# Run main function
main "$@"
